In [324]:
import pandas as pd

In [325]:
# loading data
mh = pd.read_csv("../../data/raw/mentalhealthintech.csv")
mh

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,8/27/2014 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,8/27/2014 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,8/27/2014 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,8/27/2014 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,8/27/2014 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,9/12/2015 11:17,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,9/26/2015 1:07,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,11/7/2015 12:36,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,11/30/2015 21:25,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2/1/2016 23:04,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [326]:
list(mh.columns)

['Timestamp',
 'Age',
 'Gender',
 'Country',
 'state',
 'self_employed',
 'family_history',
 'treatment',
 'work_interfere',
 'no_employees',
 'remote_work',
 'tech_company',
 'benefits',
 'care_options',
 'wellness_program',
 'seek_help',
 'anonymity',
 'leave',
 'mental_health_consequence',
 'phys_health_consequence',
 'coworkers',
 'supervisor',
 'mental_health_interview',
 'phys_health_interview',
 'mental_vs_physical',
 'obs_consequence',
 'comments']

In [327]:
mh_cleaned = mh.drop(['Timestamp', 'state', 'family_history', 'coworkers', 'Age', 'comments', 'no_employees', 'Country'], axis='columns')
mh_cleaned

,Gender,self_employed,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,Female,NaN,Yes,Often,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Yes,No,Maybe,Yes,No
1,M,NaN,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,Don't know,No
2,Male,NaN,No,Rarely,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,No,No
3,Male,NaN,Yes,Often,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,No,Maybe,Maybe,No,Yes
4,Male,NaN,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,male,No,Yes,NaN,No,Yes,No,No,No,No,Don't know,Somewhat easy,No,No,Some of them,No,No,Don't know,No
1255,Male,No,Yes,Often,Yes,Yes,Yes,Yes,No,No,Yes,Somewhat difficult,No,No,Yes,No,No,Yes,No
1256,male,No,Yes,Sometimes,No,Yes,Yes,Yes,No,No,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No
1257,f,No,No,NaN,Yes,Yes,No,Yes,No,No,Don't know,Don't know,Yes,No,No,No,No,No,No
1258,Male,No,Yes,Sometimes,No,No,Yes,Yes,No,No,Yes,Don't know,Maybe,No,No,No,No,Don't know,No

In [328]:
mh_cleaned = mh_cleaned[mh_cleaned['self_employed'].str.contains('Yes') == False]
mh_cleaned = mh_cleaned[mh_cleaned['tech_company'].str.contains('No') == False]

In [329]:
mh_cleaned = mh_cleaned.replace(['Cis Male', 'Mail', 'Make', 'Male', 'Male ', 'Male-ish', 'Malr', 'Male (CIS)', 'Male', 'Man', 'something kinda male?', 'cis male', 'm', 'maile', 'male', 'msle'], 'M')
mh_cleaned = mh_cleaned.replace(['Femake', 'Female', 'Female ', 'Female (cis)', 'Woman', 'f', 'female'], 'F')
mh_cleaned = mh_cleaned.replace(['Enby', 'non-binary', 'Agender'], 'NB')
mh_cleaned = mh_cleaned.replace(['Female (trans)', 'Trans-female'], 'MTF')
mh_cleaned = mh_cleaned.replace(['Androgyne', 'Genderqueer', 'fluid', 'male leaning androgynous', 'queer/she/they'], 'F')

In [330]:
mh_cleaned['Gender'].unique()

array(['M', 'F', 'MTF', 'NB'], dtype=object)

In [331]:
mh_cleaned = mh_cleaned.dropna(axis=0, how='any')
mh_cleaned = mh_cleaned.dropna(subset=['work_interfere'], axis=0, how='any').reset_index()

In [332]:
mh_cleaned = mh_cleaned.drop(['index', 'self_employed', 'tech_company'], axis=1)

In [335]:
mh_cleaned.to_csv('mh_cleaned_gale.csv', index=None)